load("@com_github_johnynek_bazel_deps//:def.bzl", "bazeldeps")

bazeldeps(
    name = "update-maven-deps",
    deps_file = ":dependencies.yaml",
    tags = [
        "manual",
        "no-ide",
    ],
)
